#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 19 18:51:01 2019

@author: oscar
"""

from bs4 import BeautifulSoup
import requests
import shutil
import numpy as np
import os
import random
from random import choice
import re
import time
import csv
from itertools import chain



### De esta manera se lee corretamente
read_urls= []
file=os.getcwd() + "/urls_190619.csv"
with open(file, 'rt') as myfile:
     wx = csv.reader(myfile)
     for x in wx:
         read_urls.append(x)



COSMO_list= []
k=0
while True:
    fail=1
    while True:
            try:
                ua=set_user_agents(users_list,random.randrange(0, len(users_list)))
                url1= read_urls[k]
                url=str(url1).replace('[\'', '' ).replace('\']', '')
                req= requests.get(url,
                                  headers=ua)
                
                if req.status_code == requests.codes.ok:
                    break
            except:
                pass
            print('invalid UserAgent')
            fail=fail+1
            if fail>10:
                break
    if fail>10:
        break
            
            
           
    m = re.findall('https://cosmobox.org/'
               '[^\"]+' , req.text)
    m1 = list(set(m))
    
    COSMO_list.append(m1)
    time.sleep(random.random())
    print(str(k))
    k+=1
    
    
    
    
    
file=os.getcwd()+'\urls_cosmo.csv'
with open(file, 'wb') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     for x in np.arange(0,len(prueba)):
         wr.writerow([str(prueba[x])])
